### ISSUE TITLE
[oui-datagrid]: a null value in rows break the display

### ISSUE THREAD

**Issue by Jisay** [ovh/ovh-ui-kit#563]
### Description

When a value in the rows is ```null``` the datagrid display is broken (it happens for example with Iceberg API calls).

### Steps to reproduce

1. Modify the rows array by hard coding a null value inside it.
2. Refresh the datagrid.
3. The datagrid is empty.

**Expected behavior**:

The others values (```!== null```) should be displayed into the datagrid.

**Actual behavior**:

The datagrid is empty.

**Frequency**:

It happens once an item is ```null```.

**Comment by JacquesLarique** [comment]
The problem doesn't seem to be with oui-datagrid, indeed when a null value is in a list of value given to a oui-datagrid, an empty row is displayed as seen below.

![image](https://github.com/ovh/ovh-ui-kit/assets/134954692/3f6a95e3-e426-4458-9961-deeda4bcc513)

But in some cases, like the private database users list, if a null value is given to the list controller, the display is broken because we try to access a property on each element of the list (in the case of the private database users it's the localeCompare method).

![image](https://github.com/ovh/ovh-ui-kit/assets/134954692/c3962346-6e76-42cf-824c-d16645621f91)

It will be necessary to go through every list controller where we check / map property for each list item and ensure that no item is null before accessing any of its property.

**Comment by JacquesLarique** [comment]
The problem doesn't seem to be with oui-datagrid, indeed when a null value is in a list of value given to a oui-datagrid, an empty row is displayed as seen below.
![image](https://github.com/ovh/ovh-ui-kit/assets/134954692/4daa26d4-ed44-44c3-aa45-ad5ed8355a03)
But in some cases, like the private database users list, if a null value is given to the list controller, the display is broken because we try to access a property on each element of the list (in the case of the private database users it's the localeCompare method).
![image](https://github.com/ovh/ovh-ui-kit/assets/134954692/c46c275f-c104-4dc4-9181-85939b97eb4d)
It will be necessary to go through every list controller where we check / map property for each list item and ensure that no item is null before accessing any of its property.

**Comment by anooparveti** [comment]
Following @JacquesLarique's analysis, the issue needs to be addressed from manager. So, closing the issue on `ui-kit`
